version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: itbot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - bot_network

  db:
    image: postgres:16-alpine # Using Alpine for smaller image size
    container_name: itbot_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent data storage
    ports:
      - "5432:5432" # Optional: Expose port to host for direct access (e.g., for pgAdmin)
    networks:
      - bot_network

  listener:
    container_name: itbot_listener
    build: .
    command: python main.py
    env_file:
      - .env
    volumes:
      - data-volume:/app/data
      - logs-volume:/app/logs
      - storage-volume:/app/storage
    depends_on:
      - redis
      - db # Add dependency on PostgreSQL
    restart: unless-stopped
    mem_limit: 1g
    environment: # Pass PostgreSQL connection details to the bot
      POSTGRES_HOST: db # Service name of the PostgreSQL container
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - bot_network

  worker:
    container_name: itbot_worker
    build: .
    command: python execution_worker.py
    env_file:
      - .env
    volumes:
      - data-volume:/app/data
      - logs-volume:/app/logs
      - storage-volume:/app/storage
      - ./data/analisis:/app/data/analisis
    depends_on:
      - redis
      - db # Add dependency on PostgreSQL
    restart: unless-stopped
    environment: # Pass PostgreSQL connection details to the bot
      POSTGRES_HOST: db # Service name of the PostgreSQL container
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - bot_network

volumes:
  redis-data:
  postgres_data: # New volume for PostgreSQL data
  data-volume:
  logs-volume:
  storage-volume:

networks:
  bot_network:
    driver: bridge
